# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md
#

templates:
  params:
    author-email: andreassen.kjell@gmail.com
    author-name: Kjell Andreassen
#    category: value
    copyright: Kjell Andreassen
    github-username: rashack
